# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=postgres
spring.datasource.password=aryan29jun

# JPA CONFIG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# APP CONFIG
server.port=8081
spring.application.name=loan_management