spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/loan_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_local_password}

# Required for Neon
spring.datasource.hikari.ssl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8081}
spring.application.name=loan_management

